### ISSUE TITLE
Parallel testing doesn't work

### ISSUE THREAD

**Issue by jktjkt** [CESNET/netopeer2#1020]
I'm on the latest `devel` branch, and when I try running the tests in parallel, they fail. I see that the code sets up a per-test-instance sysrepo repository, so it looks like this is something that was supposed to work. Perhaps there's a conflict on a listening port and/or a shared instance of the server?

**Comment by michalvasko** [comment]
They were not meant to work in parallel, all the setup stuff was intended to avoid failing tests because of a previous failed test. But since these tests take a lot of time it makes sense to support concurrent execution so it should now work.

**Comment by jktjkt** [comment]
Thanks, this has helped, but I'm still getting test failures as of commit 7e80c5c. This is on a 16-core CPU, and I'm getting similar results as long as I enable *any* parallelization, even with `-j2`:
```
Test project /home/jkt/work/prog/_build/czechlight-gcc-11-ly2/Netopeer2
      Start  5: test_subscribe_filter
      Start  7: test_parallel_sessions
 1/16 Test  #7: test_parallel_sessions ...........***Failed   11.49 sec
[==========] Running 1 test(s).
[  FAILED  ] GROUP SETUP
[  ERROR   ] tests
-U/home/jkt/work/prog/_build/czechlight-gcc-11-ly2/Netopeer2/tests/repositories/test_parallel_sessions/np2.sock
Setup fail in /home/jkt/work/cesnet/gerrit/github/CESNET/Netopeer2/tests/np_test.c:78.
Setup fail in /home/jkt/work/cesnet/gerrit/github/CESNET/Netopeer2/tests/np_test.c:231.
[==========] 0 test(s) run.
[  PASSED  ] 0 test(s).

      Start 12: test_sub_ntf_advanced
 2/16 Test  #5: test_subscribe_filter ............Subprocess aborted***Exception:  11.71 sec
[==========] Running 14 test(s).
[  FAILED  ] GROUP SETUP
[  ERROR   ] tests
Test failed with exception: Segmentation fault(11)

      Start 15: test_yang_push_advanced
 3/16 Test #12: test_sub_ntf_advanced ............Subprocess aborted***Exception:  11.60 sec
[==========] Running 18 test(s).
[  FAILED  ] GROUP SETUP
[  ERROR   ] tests
Test failed with exception: Segmentation fault(11)

      Start 14: test_yang_push
 4/16 Test #15: test_yang_push_advanced ..........Subprocess aborted***Exception:  11.60 sec
[==========] Running 8 test(s).
[  FAILED  ] GROUP SETUP
[  ERROR   ] tests
Test failed with exception: Segmentation fault(11)

      Start 13: test_sub_ntf_filter
 5/16 Test #13: test_sub_ntf_filter ..............   Passed    5.89 sec
      Start  6: test_subscribe_param
 6/16 Test #14: test_yang_push ...................   Passed    6.36 sec
      Start 11: test_sub_ntf
 7/16 Test  #6: test_subscribe_param .............   Passed    5.39 sec
      Start  4: test_filter
 8/16 Test #11: test_sub_ntf .....................   Passed    5.48 sec
      Start 16: test_url
 9/16 Test  #4: test_filter ......................   Passed    2.63 sec
      Start  2: test_rpc
10/16 Test #16: test_url .........................   Passed    2.63 sec
      Start  8: test_candidate
11/16 Test  #2: test_rpc .........................   Passed    2.50 sec
      Start 10: test_nacm
12/16 Test  #8: test_candidate ...................   Passed    2.55 sec
      Start  3: test_edit
13/16 Test #10: test_nacm ........................   Passed    2.91 sec
      Start  9: test_with_defaults
14/16 Test  #3: test_edit ........................   Passed    2.77 sec
      Start  1: headers
15/16 Test  #1: headers ..........................   Passed    0.18 sec
16/16 Test  #9: test_with_defaults ...............   Passed    2.39 sec

75% tests passed, 4 tests failed out of 16

Total Test time (real) =  45.02 sec

The following tests FAILED:
          5 - test_subscribe_filter (Subprocess aborted)
          7 - test_parallel_sessions (Failed)
         12 - test_sub_ntf_advanced (Subprocess aborted)
         15 - test_yang_push_advanced (Subprocess aborted)
Errors while running CTest
```
Can you reproduce this on your system?

I see that there's one test failure where the socket "doesn't appear in time", which is weird, but then there's a bunch of segfaults. I've checked one of them, and it looks like a `NULL` pointer dereference:
```
Thread 1 (LWP 2108767):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f7d8b532523 in __GI_abort () at abort.c:79
#2  0x00007f7d8b8cfafc in exit_test.part () from /nix/store/cyxdjbcc9b0c9zm22l65raicv6xd62lb-cmocka-1.1.5/lib/libcmocka.so.0
#3  0x00007f7d8b8cfbd5 in exception_handler () from /nix/store/cyxdjbcc9b0c9zm22l65raicv6xd62lb-cmocka-1.1.5/lib/libcmocka.so.0
#4  <signal handler called>
#5  0x0000000000404c6f in local_teardown (state=0x7ffd9fd0a758) at /home/jkt/work/cesnet/gerrit/github/CESNET/Netopeer2/tests/test_sub_ntf_advanced.c:116
#6  0x00007f7d8b8d346d in cmocka_run_one_test_or_fixture () from /nix/store/cyxdjbcc9b0c9zm22l65raicv6xd62lb-cmocka-1.1.5/lib/libcmocka.so.0
#7  0x00007f7d8b8d3b6f in _cmocka_run_group_tests () from /nix/store/cyxdjbcc9b0c9zm22l65raicv6xd62lb-cmocka-1.1.5/lib/libcmocka.so.0
#8  0x000000000040f415 in main (argc=1, argv=0x7ffd9fd0b3b8) at /home/jkt/work/cesnet/gerrit/github/CESNET/Netopeer2/tests/test_sub_ntf_advanced.c:1020
(gdb) up 5
#5  0x0000000000404c6f in local_teardown (state=0x7ffd9fd0a758) at /home/jkt/work/cesnet/gerrit/github/CESNET/Netopeer2/tests/test_sub_ntf_advanced.c:116
116         assert_int_equal(SR_ERR_OK, sr_set_module_replay_support(st->conn, "notif1", 0));
(gdb) print st
$1 = (struct np_test *) 0x0
```

**Comment by michalvasko** [comment]
Right, the teardown could definitely be written better but if you simply look into the server output log for each test, you will see an error with too long server socket path (if you are using latest *libnetconf2* devel). It is sadly limited to only 107 characters and it was not even checked before that it does not exceed the limit. I guess no other choice but to put all those test directories into `/tmp`.

**Comment by jktjkt** [comment]
I wasn't aware that there are log files in a directory named `repositories` :), but these are handy, thanks. Yup, these tests were using path names that were too long. Let me check if it's OK to use relative paths instead of an absolute name. If that fails, then a `$TMPDIR` might be the only resort as you say.

**Comment by jktjkt** [comment]
Thanks, everything works as expected now.
