### ISSUE TITLE
Netopeer2 connection issue.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1293]
Hi @michalvasko 
I am getting an issue of not getting a connection of `netopeer2-cli` with `netopeer2-server` here are the logs I am getting while trying to connect.

```
root@shubham:~$ netopeer2-cli 
> connect --host 192.168.0.10 --login root 
root@192.168.0.10 password: 
ly ERROR: Not found node "diffserv-markings" in path. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
ly ERROR: Target of leafref "upv4-dscp-name" cannot be referenced because it is disabled. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
cmd_connect: Connecting to the 192.168.0.10:830 as user "root" failed.
> 
```

can you please help me to solve this issue.

**Comment by michalvasko** [comment]
Seems like an issue with loading the YANG modules on the side of the client. What versions of *libnetconf2* / *netopeer2* are you using?

**Comment by Shubham-dash** [comment]
Versions I am using currently are :

```
netopeer2-server 2.1.36
netopeer2-cli 2.0.65

libnetconf2 - v1.1.43
```

**Comment by michalvasko** [comment]
Are you sure about the *libnetconf2* version? I do not think you can compile *netopeer2* v2.1.36 with *libnetconf2* v1.1.43.

**Comment by Shubham-dash** [comment]
Actually, I am not sure about the libnetconf2 version I have taken it from the master branch.

**Comment by michalvasko** [comment]
Okay, that should be fine. So you will need to provide all the installed YANG modules and the output of `sysrepoctl -l` (so that I see what features are enabled), then I should be able to reproduce it.

**Comment by Shubham-dash** [comment]
When I am trying to install `o-ran-processing-element.yang` yang module I am getting the same error. Why this is happening?
 
 ```
root@user:~$sudo sysrepoctl -i o-ran-processing-element.yang 
[ERR] Not found node "diffserv-markings" in path. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
[ERR] Target of leafref "upv4-dscp-name" cannot be referenced because it is disabled. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
sysrepoctl error: Failed to install module "o-ran-processing-element.yang" (libyang error)
For more details you may try to increase the verbosity up to "-v3".

```

**Comment by Shubham-dash** [comment]
Hi @michalvasko 
I can't resolve this issue 
```

[ERR] Not found node "diffserv-markings" in path. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
[ERR] Target of leafref "upv4-dscp-name" cannot be referenced because it is disabled. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
sysrepoctl error: Failed to install module "o-ran-processing-element.yang" (libyang error)
For more details you may try to increase the verbosity up to "-v3".

```

Can you please give me clue about this?
attaching zip of `o-ran-processing-element.yang` and `o-ran-interfaces.yang`

[yangmodules.zip](https://github.com/CESNET/netopeer2/files/9958204/yangmodules.zip)

**Comment by michalvasko** [comment]
What I have said before is exactly right, the YANG modules are **invalid**. The leaf `upv4-dscp-name` is not dependent on any features whereas the container in the target path is. It is the container `diffserv-markings` that is in a grouping, which is added by an augment with `if-feature UDPIP-BASED-CU-PLANE`. See the [sec 9.9., last paragraph](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.9) for reference.

**Comment by jamespark76** [comment]
Hello all,

This issue was fixed in M-Plane v10.0

```
O-RAN.WG4.MP-YANGs-v10.00.zip
o-ran-processing-element.yang (revision 2022-08-15)

case ipv4 {
  when "(../../transport-session-type = 'UDPIP-INTERFACE')";
  leaf upv4-dscp-name {
   if-feature o-ran-int:UDPIP-BASED-CU-PLANE;
    type leafref {
      path "/if:interfaces/if:interface/ip:ipv4/o-ran-int:diffserv-markings/o-ran-int:enhanced-uplane-markings/o-ran-int:up-marking-name";
    }
    description "the IPv4 U-plane transport marking as defined in o-ran-interfaces";
  }
}
```

Best Regards,

**Comment by RichardZeyu** [comment]
> Hello all,
> 
> This issue was fixed in M-Plane v10.0
> 
> ```
> O-RAN.WG4.MP-YANGs-v10.00.zip
> o-ran-processing-element.yang (revision 2022-08-15)
> 
> case ipv4 {
>   when "(../../transport-session-type = 'UDPIP-INTERFACE')";
>   leaf upv4-dscp-name {
>    if-feature o-ran-int:UDPIP-BASED-CU-PLANE;
>     type leafref {
>       path "/if:interfaces/if:interface/ip:ipv4/o-ran-int:diffserv-markings/o-ran-int:enhanced-uplane-markings/o-ran-int:up-marking-name";
>     }
>     description "the IPv4 U-plane transport marking as defined in o-ran-interfaces";
>   }
> }
> ```
> 
> Best Regards,

hello, I use sysrepoctl reinstall new module "o-ran-processing-element"(2022-08-15 version), still show that:

> [ERR] Not found node "diffserv-markings" in path. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)

> [ERR] Target of leafref "upv4-dscp-name" cannot be referenced because it is disabled. (Schema location "/o-ran-processing-element:processing-elements/enhanced-uplane-mapping/uplane-mapping/up-markings/ipv4/upv4-dscp-name".)
sysrepoctl error: Failed to install module "o-ran-processing-element.yang" (libyang error)
