### ISSUE TITLE
edit-config failed for leaf-list

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#46]
module
```
module t{
  namespace "ttt:1";
  prefix t;

  container c1{
    leaf-list lf1{
      type int8;
    }
  }
}
```
data:
```
<c1 xmlns="ttt:1">
<lf1>10</lf1>
</c1>
```
result:
```
> edit-config --target running --config=/root/z-conf/mymodules/e5g/d.xml
OK
> 
> 
> edit-config --target running --config=/root/z-conf/mymodules/e5g/d.xml
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Invalid argument
> 
```
**notice that it only failed in the second time.**
sysrepod print some error:
```
[INF] (rp_dt_set_item_wrapper:559) Set item request running datastore, xpath: /t:c1/lf1[.='10']
[DBG] (dm_get_data_info:1701) Module t already loaded
[DBG] (dm_ly_log_cb:815) libyang error: Unexpected character(s) '[' ([.='10']).
[ERR] (rp_dt_set_item:423) Setting of item failed /t:c1/lf1[.='10'] 65
[ERR] (rp_dt_set_item_wrapper:574) Set item failed
[ERR] (rp_set_item_req_process:919) Set item failed for '/t:c1/lf1[.='10']', session id=2024596807.
```

**Comment by michalvasko** [comment]
Hi,
it should be fixed in the current libyang version, please pull it and try again.

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
it works when there is only 1 instance, but when there are more than 1 instances, it still failed.
try this data:
```
<c1 xmlns="ttt:1">
<lf1>10</lf1>
<lf1>12</lf1>
<lf1>11</lf1>
</c1>
```
result:
```
[DBG] (rp_dt_commit:688) Commit (1/9): process started
[DBG] (dm_ly_log_cb:815) libyang error: Duplicated instance of "lf1" leaf-list ("12").
[DBG] (dm_validate_session_data_trees:2123) Validation failed for t module
[ERR] (rp_dt_commit:694) Data validation failed: Duplicated instance of "lf1" leaf-list ("12").
```

**Comment by michalvasko** [comment]
Hi,
please try it again and hopefully this time it will all work the way it is expected.

Regards,
Michal

**Comment by fanchanghu** [comment]
it's ok now, thanks very much.
