### ISSUE TITLE
server installation fails: Input data are not valid: Leafref "/ietf-system-keychain:keychain/ietf-system-keychain:private-keys/ietf-system-keychain:private-key/ietf-system-keychain:name" of value "ssh_host_rsa_key" points to a non-existing leaf. (/ietf-netconf-server:netconf-server/listen/endpoint[name='main_ssh']/ssh/host-keys/host-key[name='host_key']/public-key)

### ISSUE THREAD

**Issue by jktjkt** [CESNET/Netopeer2#54]
```
[root@f25 build-server]# PKG_CONFIG_PATH=/usr/lib/pkgconfig cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -DCMAKE_INSTALL_PREFIX=/usr ../server && ninja-build && ninja-build install 
-- The C compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
Package authd was not found in the pkg-config search path.
Perhaps you should add the directory containing `authd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'authd' found
-- Failed to learn authd keys directory, set AUTHD_KEYS_DIR manually or server configuration will not work.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - found
-- Found sysrepo: /usr/lib/libsysrepo.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/netopeer2/build-server
[13/14] Building C object CMakeFiles/netopeer2-server.dir/main.c.o
/root/netopeer2/server/main.c: In function ‘np2srv_init_schemas’:
/root/netopeer2/server/main.c:327:62: warning: passing argument 2 of ‘sr_module_install_subscribe’ from incompatible pointer type [-Wincompatible-pointer-types]
         rc = sr_module_install_subscribe(np2srv.sr_sess.srs, np2srv_module_install_clb, NULL, 0, &np2srv.sr_subscr);
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/netopeer2/server/main.c:32:0:
/usr/include/sysrepo.h:1251:5: note: expected ‘sr_module_install_cb {aka void (*)(const char *, const char *, enum sr_module_state_e,  void *)}’ but argument is of type ‘void (*)(const char *, const char *, _Bool,  void *)’
 int sr_module_install_subscribe(sr_session_ctx_t *session, sr_module_install_cb callback, void *private_ctx,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[14/14] Linking C executable netopeer2-server
[0/1] Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/bin/netopeer2-server
-- Importing module ietf-netconf-server into sysrepo...
CMake Error at cmake_install.cmake:143 (message):
    Command sysrepocfg import failed:
    [ERR] (srcfg_import_datastore:676) Input data are not valid: Leafref "/ietf-system-keychain:keychain/ietf-system-keychain:private-keys/ietf-system-keychain:private-key/ietf-system-keychain:name" of value "ssh_host_rsa_key" points to a non-existing leaf. (/ietf-netconf-server:netconf-server/listen/endpoint[name='main_ssh']/ssh/host-keys/host-key[name='host_key']/public-key)
    Errors were encountered during importing. Cancelling the operation.
    


FAILED: CMakeFiles/install.util 
cd /root/netopeer2/build-server && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Comment by milanlenco** [comment]
Hi,
This is actually an issue in sysrepo. Should be fixed now in the master branch.

**Comment by michalvasko** [comment]
Hi,
I am still seeing the error, am I doing something wrong or there is still some problem, does netopeer2 devel-server branch server install work for you (with having authd installed)?

Regards,
Michal

**Comment by milanlenco** [comment]
Right, I forgot to mention that I had to add a (fake) entry for "ssh_host_rsa_key" into the `private-keys` list of `keychain` container in the `ietf-system-keychain` module. Otherwise the leafref validation (correctly) fails. I believe this should be part of default config installation.

The bug that I have fixed was that sysrepo wouldn't merge data trees of `ietf-netconf-server` and `ietf-system-keychain` for validation and so the leafref would point to non-existing leaf regardless of the `ietf-system-keychain` content.

**Comment by michalvasko** [comment]
Hi Milan,
adding the entry is part of authd installation and I have it too. I'll try to properly update my sysrepo installation and report back because I keep seeing the error.

Michal

PS: Sorry, I moved my post because I thought you have not seen it.

**Comment by milanlenco** [comment]
My output:
```
~/dev/Netopeer2/server/build $ make clean
~/dev/Netopeer2/server/build $ make
[  4%] Building C object CMakeFiles/serverobj.dir/ietf_netconf_server.c.o
[  9%] Building C object CMakeFiles/serverobj.dir/netconf_monitoring.c.o
[ 13%] Building C object CMakeFiles/serverobj.dir/operations.c.o
[ 18%] Building C object CMakeFiles/serverobj.dir/op_get_config.c.o
[ 22%] Building C object CMakeFiles/serverobj.dir/op_editconfig.c.o
[ 27%] Building C object CMakeFiles/serverobj.dir/op_copyconfig.c.o
[ 31%] Building C object CMakeFiles/serverobj.dir/op_deleteconfig.c.o
[ 36%] Building C object CMakeFiles/serverobj.dir/op_candidate.c.o
[ 40%] Building C object CMakeFiles/serverobj.dir/op_validate.c.o
[ 45%] Building C object CMakeFiles/serverobj.dir/op_un_lock.c.o
[ 50%] Building C object CMakeFiles/serverobj.dir/op_generic.c.o
[ 54%] Building C object CMakeFiles/serverobj.dir/log.c.o
[ 54%] Built target serverobj
[ 59%] Building C object CMakeFiles/netopeer2-server.dir/main.c.o
[ 63%] Linking C executable netopeer2-server
[ 63%] Built target netopeer2-server
[ 68%] Building C object tests/CMakeFiles/test_un_lock.dir/test_un_lock.c.o
[ 72%] Linking C executable test_un_lock
[ 72%] Built target test_un_lock
[ 77%] Building C object tests/CMakeFiles/test_get.dir/test_get.c.o
[ 81%] Linking C executable test_get
[ 81%] Built target test_get
[ 86%] Building C object tests/CMakeFiles/test_close_session.dir/test_close_session.c.o
[ 90%] Linking C executable test_close_session
[ 90%] Built target test_close_session
[ 95%] Building C object tests/CMakeFiles/test_edit_get_config.dir/test_edit_get_config.c.o
[100%] Linking C executable test_edit_get_config
[100%] Built target test_edit_get_config
/dev/Netopeer2/server/build $ sudo make install
[ 54%] Built target serverobj
[ 63%] Built target netopeer2-server
[ 72%] Built target test_un_lock
[ 81%] Built target test_get
[ 90%] Built target test_close_session
[100%] Built target test_edit_get_config
Install the project...
-- Install configuration: "debug"
-- Installing: /usr/local/bin/netopeer2-server
-- Set runtime path of "/usr/local/bin/netopeer2-server" to ""
-- Importing module ietf-netconf-server into sysrepo...
-- Default NETCONF server configuration imported (SSH listen on 0.0.0.0:830).
~/dev/Netopeer2/server/build $ sudo cat /home/mlenco/dev/sysrepo/build/repository/data/ietf-system-keychain.startup                                                                                                 
<keychain xmlns="urn:ietf:params:xml:ns:yang:ietf-system-keychain">
  <private-keys>
    <private-key>
      <name>ssh_host_rsa_key</name>
    </private-key>
  </private-keys>
</keychain>
~/dev/Netopeer2/server/build $ sudo cat /home/mlenco/dev/sysrepo/build/repository/data/ietf-netconf-server.startup
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>main_ssh</name>
      <ssh>
        <address>0.0.0.0</address>
        <host-keys>
          <host-key>
            <name>host_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>
```

**Comment by michalvasko** [comment]
Hi,
it finally works for me, something was not being updated, thanks. So I consider this issue fixed.

Michal
