### ISSUE TITLE
Core dump error on netopeer2 using bindings

### ISSUE THREAD

**Issue by IvanAguiar** [CESNET/netopeer2#594]
Hi,

This error occurs when we create a rpc subscription (get, for example) and call it a couple of times, it looks to work fine on the first times.

We're doing this way:
```
import sysrepo as sr
def cb_get(cb_session, op_path, input, event, request_id, output, private_data):
    print("call cb get ")
    return sr.SR_ERR_OK
try:
    connection = sr.Connection()
    sess = sr.Session(connection, sr.SR_CONN_DEFAULT)
    subscribe = sr.Subscribe(sess)
    print("------------------------------- LISTENING RPCs -----------------------------")
    try:
        subscribe.rpc_subscribe("/ietf-netconf:get", cb_get)
    except Exception as e:
        print(e)
    sr.global_loop()
except Exception as e:
    print(e)
```

and getting this on server 
![01-ERROR-NETCONF-SERVER](https://user-images.githubusercontent.com/49284882/79581526-e565d400-80a0-11ea-9a11-040d5e3d44e6.png)
and this on CLI
![01-CLI-ERROR](https://user-images.githubusercontent.com/49284882/79581600-08908380-80a1-11ea-828e-51d86cb8ac52.png)

It occurs in both

> libyang - v1.0.130
> sysrepo - v1.4.2
> libnetconf2 - v1.1.7
> Netopeer2 - v1.1.7

and 
​
>libyang - v1.0.109
>sysrepo - v1.3.21
>libnetconf2 - v1.1.3
> Netopeer2 - v1.1.1

Additionaly, sometimes we got the full response even passing the xpath filter, and sometimes we got the filtered data.

Best regards,
Ivan

**Comment by michalvasko** [comment]
Hi Ivan,
could you please try to also use the latest `devel` version (of all *libyang*, *libnetconf2*, *netopeer2*, and *sysrepo*)? It may have been fixed.

Regards,
Michal

**Comment by IvanAguiar95** [comment]
Hi Michal,

Unfortunatelly this issue is not related with the above issue. 

We verified this issue on the last release, but this issue still occurrs.

I'm attaching the valgrind logs.

[output_rpc_error.txt](https://github.com/CESNET/netopeer2/files/4636847/output_rpc_error.txt)

BR,
Ivan
