### ISSUE TITLE
Netopeer2 support on QNX platform

### ISSUE THREAD

**Issue by apropp-molex** [CESNET/Netopeer2#598]
Hi Michal,

So I see that there are a couple of issues open pertaining to QNX, but none really went anywhere. As usual, I've summarized my issues below. Let me know if you need more details or anything else. Thanks for your help thus far.

In terms of both `cli` and `server` I ran into some issues:
1. Manually specifying `-DLIBSSH_LIBRARY` and `-DLIBSSH_INCLUDE_DIR` had no effect, unlike with `libnetconf2`. This caused it to be perceived that `libnetconf2` wasn't compiled with ssh support when it was really a missing header issue.
1. Both needed in some form the usual GNU/non-QNX functions: `asprintf`, `getline`, `vasprintf` and `strndup`. This issue has been dealt with for `libyang`, `sysrepo` and `libnetconf2`. Would it be possible to do here as well?
1. Due to issue 1, obviously linking with the `-lssh` flag failed.

The `cli` had a few other functions missing that were GNU extensions:
1. `sendfile` - could be done with `read/write`
1. `strchrnul` - `strchr` is on QNX
1. `strdupa` - `strdup` and `alloca` are on QNX as well

With the server, as I couldn't specify where to look for `libssh` files, it opted to link against `-lssh_threads`. Given that I'm pulling from the top of master, that obviously won't link. `-lcrypt` also tried to link but as discussed in `libnetconf2` this is implemented with `-llogin` on QNX.

**Comment by michalvasko** [comment]
Hi,
so please try the current `devel-server`, most of the issues should be fixed. Actually, I am hoping that all of them are except for the specific `netopeer2-cli` missing functions. Please provide a pull request for that so that `sendfile` is not used at all and `strchrnul` and `strdupa` are added to the *compat* used in *netopeer2* with all needed checks.

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

Tried the current `devel-server`. `netopeer2-server` builds fine. `netopeer2-cli` still doesn't make use of `-DLIBSSH_LIBRARY` and `-DLIBSSH_INCLUDE_DIR`. This leads to issues with finding header files and the `.so` files. Any thoughts on this?
Pull request has been provided for the missing functions.

**Comment by michalvasko** [comment]
Hi,
you have not mentioned CLI before so I just assumed the old `FindLibSSH` from `master` was causing problems. Also, why should the CLI be linked with *libssh*? It should not be using any functions from it, I have checked just now.

As for the duplicate definition, probably a leftover from when I was deciding what macros to define to cover all the functions. Fixed.

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

Thanks for clearing up the duplicate definition. As for the other issue, I've opted to install the cross-compiled `libssh` in `/usr/local` instead of `usr/local1` (my fiction) as that's what `/usr/local` is for: stuff built by the admin. That fixed it.
If you're curious, it only manifested with the cli because as you said the cli doesn't link against `libssh`. So when it went to link against `libnetconf2`, `libnetconf2` was confused as to where to find `libssh` since it wasn't specified with the symbols mentioned above. In the case of the server and `libnetconf2` I was able to specify the path to libssh itself and its headers.
I know this isn't what issues are for, but do you know of any better ways to deal with cross-compiled libraries?

**Comment by michalvasko** [comment]
Hi,
I have no experience with cross-compiling (@jktjkt does) but I think this is not a problem specific to that. If you managed to compile and install *libnetconf2*, then *libssh* must have been found when it was compiled. Not being found when linking against *libnetconf2* later is the dynamic linker (`ld(1)`) problem, at least that is what makes sense to me. If so, then there should be several ways how this can be fixed, it is a general Linux problem. The most ad-hoc is to define `LD_PRELOAD` variable with the specific library to link. A more convenient solution would be to add all the paths you have libraries in (such as `/usr/local1/lib`) to the paths searched by `ld` (files `/etc/ld.so.conf` and content of `/etc/ld.so.conf.d/`). You can use `ldconfig` to refresh the list of dynamic libraries on your system and `ldconfig -p` to print all the current found ones (so you can do `ldconfig -p | grep libssh`).

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

Thanks for the tips. I'll close this issue off now.
