### ISSUE TITLE
netopeer2-server crashed when try to add data via edit-config

### ISSUE THREAD

**Issue by xheke** [CESNET/netopeer2#912]
Hi Michal, 

I update libyang/sysrepo/netopeer2  with the last code today,
I try to add data by netopeer2 cli,  but netopeer2 srv crashed abnormally.

Then I add the same data by sysrepo, it is success without any error, and can be queried by netopeer2 cli. 

The same behavior can be done with old version(based on 2021/05/18) 
but can not work on today version( 2021/06/04)

Related information as following:

```
> onfig --target running --config=/mnt/sysrepo.example/c.nc.platform.power.replace.xml --rpc-timeout 20
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.
```

```
netopeer2-server: /src/CESNET/libyang/src/parser_xml.c:377: lydxml_data_check_opaq: Assertion `xmlctx->status == LYXML_ELEM_CONTENT' failed.
Aborted (core dumped)
```

```
<components xmlns="http://openconfig.net/yang/platform"
xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
xc:operation="replace">
<component>
<name>abc</name>
<config>
<name>abc</name>
</config>
<power-supply>
<config>
<enabled xmlns="http://openconfig.net/yang/platform/psu">false</enabled>
</config>
</power-supply>
</component>
</components>
```

```
libyang commit: 6f74fd18e5ace7d8f1ae6c1c1c2b7442dc263b22
Date:   Thu Jun 3 10:17:37 2021 +0200
```

```
netopeer2 commit:  61161666230f5f1af51683089b55505424756f4a
Date:   Thu Jun 3 15:31:14 2021 +0200
```

I'm not sure it is netopeer2 issue or libyang issue, seems sysrepo work fine, it is just crashed on netopeer2 side.

Thanks,

**Comment by michalvasko** [comment]
The *libyang* commit you posted is really the last but the assert
```
netopeer2-server: /src/CESNET/libyang/src/parser_xml.c:377: lydxml_data_check_opaq: Assertion `xmlctx->status == LYXML_ELEM_CONTENT' failed.
```
is not on the line in the crash meaning you have not properly updated your libraries and tools. The problem is solved in the current `devel` so it is up to you to fix your installation.

**Comment by xheke** [comment]
Hi Michal,

I have some confusion.

Just now, I use clean  container and install all modules, but crash still happened.
Do you mean, I need change current branch (libyang)  from master to devel , is that right?

**Comment by michalvasko** [comment]
No, I mean you are not actually running the revision you said you are. In that revision, there is no assert on [line 377](https://github.com/CESNET/libyang/blob/devel/src/parser_xml.c#L377) because the issue was fixed and the assert moved to [line 383](https://github.com/CESNET/libyang/blob/devel/src/parser_xml.c#L383). Please, try to be more self-sufficient and independent, I do not provide help with basic Linux problems.

**Comment by xheke** [comment]
Hi Michal,

It is very strange, I just check it on the devel branch,  and see the code is aligned as you said.
But master did not match you said, please  see below information.
(I just test it on devel, it is ok with no crash.) 

```
1031859.hk.src[root@vm-nat-gw-base libyang]# git branch -vv
* devel  d77e5af8 [origin/devel] build REFACTOR separate code coverage into a module
  master 6f74fd18 [origin/master] actions REFACTOR separate devel push actions
```

```
377:
      while (xmlctx->status == LYXML_ATTRIBUTE) {
```

```
1031859.hk.src[root@vm-nat-gw-base src]# git branch -vv     
  devel  d77e5af8 [origin/devel] build REFACTOR separate code coverage into a module
* master 6f74fd18 [origin/master] actions REFACTOR separate devel push actions
```

```
377:
 377         assert(xmlctx->status == LYXML_ELEM_CONTENT);
```

**Comment by michalvasko** [comment]
I am completely confused, you referenced commit from `devel`, I have told you to use latest `devel` and now you say you were using `master`.

**Comment by xheke** [comment]
Sorry, I always use master branch as default.

I'm not aware we should use `devel` before.  do we always use `devel` branch for test?

**Comment by michalvasko** [comment]
Whenever you want latest bug fixes, you should always use `devel`.

**Comment by xheke** [comment]
Ok, thanks Michal, I got it.
